# Generated by Django 4.2.3 on 2023-07-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='careers/')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
